version: "3.9"
services:
  api:
    build: .
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - files:/app/uploads:rw
      - data:/app/requestlogs:rw
      - /etc/letsencrypt/live/:/app/certs:ro
    depends_on:
      - "mongo"
      - "redis"
    links:
      - "mongo:database"
      - "redis:auth"
    restart: unless-stopped
  mongo:
    image: "mongo:latest"
    volumes:
      - db:/data/db
    restart: unless-stopped
  redis:
    image: "redis:latest"
    restart: unless-stopped
volumes:
  data: {}
  files: {}
  db: {}
