version: "3.9"
services:
  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - files:/app/uploads:rw
      - data:/app/requestlogs:rw
    depends_on:
      - "mongo"
      - "redis"
    links:
      - "mongo:database"
      - "redis:auth"
  mongo:
    image: "mongo:4.4.10"
    volumes:
      - db:/data/db
  redis:
    image: "redis:latest"
volumes:
  data: {}
  files: {}
  db: {}
