version: "3.9"
services:
  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - api-data:/app/uploads:rw
      - api-data:/app/requestlogs:rw
    depends_on:
      - "mongo"
      - "redis"
    links:
      - "mongo:database"
      - "redis:auth"
  mongo:
    image: "mongo:latest"
    volumes:
      - api-data:/data/db
  redis:
    image: "redis:latest"
volumes:
  api-data:
