version: "3.9"
services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - "mongo"
    links:
      - "mongo:database"
  mongo:
    image: "mongo:latest"
    volumes:
      - ~/persistance/mongo/:/data/db
