version: "3.9"
services:
  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ~/persistance/api/uploads:/app/uploads:rw
      - ~/persistance/api/requestLogs:/app/requestLogs:rw
    depends_on:
      - "mongo"
      - "redis"
    links:
      - "mongo:database"
      - "redis:auth"
  mongo:
    image: "mongo:latest"
    volumes:
      - ~/persistance/mongo/:/data/db
  redis:
    image: "redis:latest"
